Repository HSUProject/BuFF, pull requests merged in 2023-05, with the labels that each got.

#12 Update volume deformation to GPU
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: bug, enhancement, help wanted

#14 improve reset performance
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: enhancement

#15 Update Deform Index
  src/testbed_nerf.cu
Labels: bug

#16 Add CUDA Texture Object
  src/testbed_nerf.cu
Labels: enhancement

#17 Update volume deformation
  src/testbed.cu
  src/testbed_nerf.cu
Labels: bug, enhancement

#18 UI update
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: bug, enhancement

#19 Update volume deformation structure
  include/neural-graphics-primitives/testbed.h
  src/testbed_nerf.cu
Labels: enhancement

#20 Fixed undo, redo and reset deformations
  src/testbed.cu
  src/testbed_nerf.cu
Labels: bug

#21 Add Visualize Mouse Position
  src/testbed.cu
Labels: enhancement

#22 Update UI and deformation
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: enhancement

#24 Fixed scale of user input direction
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
Labels: bug

#25 UI
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
Labels: enhancement

#26 Update README
  README.md
  scripts/colmap2nerf.py
Labels: documentation, enhancement
