Repository HSUProject/BuFF, pull requests merged in 2023-04, with the labels that each got.

#2 Add volume data structure
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: enhancement

#3 Update user input
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: enhancement

#4 Fixed volume data structure
  src/testbed_nerf.cu
Labels: bug

#6 Add deform code
  src/testbed_nerf.cu
Labels: enhancement

#7 Add revert deform code
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: enhancement

#9 UI update
  include/neural-graphics-primitives/testbed.h
  src/python_api.cu
  src/testbed.cu
  src/testbed_nerf.cu
Labels: enhancement

#8 Update revert deform
  src/testbed.cu
  src/testbed_nerf.cu
Labels: bug, enhancement

#10 Update recovery deform
  include/neural-graphics-primitives/testbed.h
  src/testbed.cu
  src/testbed_nerf.cu
Labels: enhancement

#11 UI update
  src/testbed.cu
Labels: enhancement
